- papercut/ng_mf/CVE-2023-27350/Dockerfile
- papercut/ng_mf/CVE-2023-27350/Readme.md
- papercut/ng_mf/CVE-2023-27350/assets/cupsd.conf
- papercut/ng_mf/CVE-2023-27350/assets/image_setup.py
- papercut/ng_mf/CVE-2023-27350/assets/server.properties
- papercut/ng_mf/CVE-2023-27350/assets/setup.sh
- papercut/ng_mf/CVE-2023-27350/assets/startup.sh
- papercut/ng_mf/CVE-2023-27350/docker-bake.hcl
- papercut/ng_mf/CVE-2023-27350/local_builder.sh
Adding the papercut dockerfiles and assets needed for the testbed
> Papercut CVE 2023 27350 - Testbed files

- php/arbitrary_file_write_php/Dockerfile
- php/arbitrary_file_write_php/README.md
- php/arbitrary_file_write_php/index.php
- php/arbitrary_file_write_php/startup.sh
A PHP webapp vulnerable to Arbitrary File Write with a CRON daemon in a docker container
This webapp can be used for testing arbitrary file write exploitation. 
It was originally created to test file write to RCE via crontab payload (linux_root_crontab).
> PHP webapp with an Arbitrary File Write vuln in a docker container with crond installed

- jenkins/CVE-2024-23897/README.md
relate to [#380](https://github.com/google/tsunami-security-scanner-plugins/issues/380)
> feat: add docker images related to CVE-2024-23897

- mlflow/CVE-2023-6014/README.md
Hi,
I added vulnerable configuration for this [AI PRP Request](https://github.com/google/tsunami-security-scanner-plugins/issues/427).
> Add Vulnerable Environment for CVE-2023-6014

- apache/spark/CVE-2022-33891/README.md
- apache/spark/CVE-2022-33891/fixed-docker-compose.yml
- apache/spark/CVE-2022-33891/vuln-docker-compose.yml
Hi,
I am adding vulnerable configuration for this https://github.com/google/tsunami-security-scanner-plugins/issues/430.
> Add vulnerable docker files for CVE-2022-33891

- apache/airflow/CVE-2020-17526/README.md
- apache/airflow/CVE-2020-17526/docker-compose-secure.yml
- apache/airflow/CVE-2020-17526/docker-compose-vulnerable.yml
- apache/airflow/CVE-2020-17526/init-user.py
As this is a RCE with OOB callback I don't think we need a setup for patched version!
https://github.com/google/tsunami-security-scanner-plugins/issues/428
> CVE-2020-17526 Auth Bypass in Airflow lead into RCE 

- mlflow/weak_credentials/README.md
Hi, this PR is according to @maoning's request from here:
https://github.com/google/tsunami-security-scanner-plugins/issues/412
> Weak Credential Tester for MLflow

- apache/airflow/ExposedUI/DockerfileSafe
- apache/airflow/ExposedUI/DockerfileUnSafe
- apache/airflow/ExposedUI/README.md
- apache/airflow/ExposedUI/docker-compose.yml
- apache/airflow/ExposedUI/webserver_config_safe.py
- apache/airflow/ExposedUI/webserver_config_unsafe.py
https://github.com/google/tsunami-security-scanner-plugins/issues/413
> Airflow Exposed UI 

- apache/activemq/CVE-2023-46604/README.md
- apache/activemq/CVE-2023-46604/activemq-cve-2023-46604.yaml
- apache/activemq/CVE-2023-46604/docker-compose.yml
@tooryx  This is about the vulnerability environment submission for Apache ActiveMQ[CVE-2023-46604].
> Add vulnerability environment for CVE-2023-46604.

- anything-llm/CVE-2024-3104/Dockerfile
- anything-llm/CVE-2024-3104/README.md
- anything-llm/CVE-2024-3104/docker-compose.yml
- anything-llm/CVE-2024-3104/setup.sh
Hi,
This is vulnerable environment for CVE-2024-3104. Related issue is https://github.com/google/tsunami-security-scanner-plugins/issues/504
> Add config for CVE-2024-3104

- atlassian/bitbucket/CVE-2022-36804/README.md
https://github.com/google/tsunami-security-scanner-plugins/pull/267
> add CVE-2022-36804  vulnerability environment

- apache/hive/weak_credentials/README.md
- apache/hive/weak_credentials/base.ldif
- apache/hive/weak_credentials/docker-compose.yml
- apache/hive/weak_credentials/hive-site.xml
testbeds for https://github.com/google/tsunami-security-scanner-plugins/issues/418
> feat: update testbeds for hive

- bentoml/Dockerfile
- bentoml/README.md
- bentoml/docker-compose-safe.yml
- bentoml/docker-compose-vulnerable.yml
- bentoml/exploit.py
- bentoml/service.py
Hi, according to my tsunami plugin: https://github.com/google/tsunami-security-scanner-plugins/pull/520
> bentoml insecure deserlization plugin

- ollama/exposed_api/README.md
- ollama/exposed_api/docker-compose.yml
In reference to https://github.com/google/tsunami-security-scanner-plugins/pull/637
> Add testbed for exposed Ollama API Server

- kestra/exposed_ui/README.md
Kestra Exposed UI tested by out-of-band
https://github.com/google/tsunami-security-scanner-plugins/issues/605
> kestra exposed UI

- apache/axis2/weak_credentials/README.md
- apache/axis2/weak_credentials/axis2_secured/Dockerfile
- apache/axis2/weak_credentials/axis2_secured/config/axis2.xml
- apache/axis2/weak_credentials/axis2_secured/config/server.xml
- apache/axis2/weak_credentials/axis2_unsecured/Dockerfile
- apache/axis2/weak_credentials/axis2_unsecured/config/axis2.xml
- apache/axis2/weak_credentials/axis2_unsecured/config/server.xml
Hi,
I have added testbed for the Apache Axis2 weak credentials.
Regards,
> Add support to Apache Axis2 weak credentials tester

- bash/CVE-2014-6271/Dockerfile
- bash/CVE-2014-6271/README.md
- bash/CVE-2014-6271/docker-compose.yml
- bash/CVE-2014-6271/safe.cgi
- bash/CVE-2014-6271/vuln.cgi
Hello,
this PR adds the testbed for CVE-2014-6271.
> add CVE-2014-6271 testbed

- kafkaui/cve-2023-52251/README.md
- kafkaui/cve-2023-52251/docker-compose.yml
https://github.com/google/tsunami-security-scanner-plugins/pull/658
https://github.com/google/tsunami-security-scanner-plugins/issues/510
> Kafka-ui CVE-2023-52251 RCE

- erlang-otp/CVE-2025-32433/Dockerfile
- erlang-otp/CVE-2025-32433/README.md
- erlang-otp/CVE-2025-32433/exploit.py
- erlang-otp/CVE-2025-32433/ssh_server.erl
Hello, this is regarding the PRP  https://github.com/google/tsunami-security-scanner-plugins/issues/633
> Erlang/OTP SSH Server RCE CVE-2025-32433

- k8s/exposed_ui/.gitignore
- k8s/exposed_ui/README.md
- k8s/exposed_ui/cleanup.sh
- k8s/exposed_ui/config.yaml
- k8s/exposed_ui/exploit.sh
- k8s/exposed_ui/setup.sh
https://github.com/google/tsunami-security-scanner-plugins/pull/670
> K8s Dashboard without authentication

- supabase/exposedui/README.md
- supabase/exposedui/start.sh
[PRP: supabase ExposedUI RCE with default configuration](https://github.com/google/tsunami-security-scanner-plugins/issues/671)
https://github.com/google/tsunami-security-scanner-plugins/issues/671
> v1: Supabase RCE
